-- CSY2026 Group 22 Assignment Inserts
INSERT INTO customers
VALUES (seq_c_id.NEXTVAL, 'MR', 'BROOK', 'SMITH',
'GRANGE FARM DRIVE', 'STOCKTON', 'WARWICKSHIRE',
'CV37 8FT', 'UNITED KINGDOM', '07000000000',
'BROOKSMITH@EMAIL.COM', 'M');

INSERT INTO customers
VALUES (seq_c_id.NEXTVAL, 'MISS', 'AMBER', 'RAWLINS',
'AVENUE CAMPUS', 'NORTHAMPTON', 'NORTHAMPTONSHIRE',
'NN2 6JD', 'UNITED KINGDOM', '07000000001',
'AMBERRAWLINS@EMAIL.COM', 'F');

INSERT INTO customers
VALUES (seq_c_id.NEXTVAL, 'MISS', 'ALAN', 'MEADE',
'STEAVE ROAD', 'NORTHAMPTON', 'NORTHAMPTONSHIRE',
'NN2 3FM', 'UNITED KINGDOM', '07000000002',
'ALANMEADE@EMAIL.COM', 'M');

INSERT INTO customers
VALUES (seq_c_id.NEXTVAL, 'MR', 'ALFIE', 'ENGLAND',
'CARAVAN ROAD', 'LONG ITCHINGTON', 'WARWICKSHIRE',
'CV47 SA3', 'UNITED KINGDOM', '07000000003',
'ALFIEENGLAND@EMAIL.COM', 'M');

INSERT INTO customers
VALUES (seq_c_id.NEXTVAL, 'MR', 'THOMAS', 'WEAVER',
'WEEBLE ROAD', 'LINCON', 'LINCONSHIRE',
'SA12 ME4', 'UNITED KINGDOM', '07000000004',
'THOMASWEAVER@EMAIL.COM', 'M');

INSERT INTO locations
VALUES (seq_l_id.NEXTVAL, seq_l_coutid.NEXTVAL, 'SPAIN',
seq_l_hotid.NEXTVAL, 'BUMBALATTE', 'COAST');

INSERT INTO locations
VALUES (seq_l_id.NEXTVAL, seq_l_coutid.NEXTVAL, 'MALTA',
seq_l_hotid.NEXTVAL, 'JEFF', 'COAST');

INSERT INTO locations
VALUES (seq_l_id.NEXTVAL, seq_l_coutid.NEXTVAL, 'NETHERLANDS',
seq_l_hotid.NEXTVAL, 'DANKL', 'URBAN');

INSERT INTO locations
VALUES (seq_l_id.NEXTVAL, seq_l_coutid.NEXTVAL, 'FRANCE',
seq_l_hotid.NEXTVAL, 'KING LOUIE', 'URBAN');

INSERT INTO locations
VALUES (seq_l_id.NEXTVAL, seq_l_coutid.NEXTVAL, 'TURKEY',
seq_l_hotid.NEXTVAL, 'HARRY', 'COAST');

INSERT INTO hotels
VALUES (seq_h_hotid.NEXTVAL, 'BUMBALATTE', 40, seq_h_lotid.NEXTVAL);

INSERT INTO hotels
VALUES (seq_h_hotid.NEXTVAL, 'JEFF', 40, seq_h_lotid.NEXTVAL);

INSERT INTO hotels
VALUES (seq_h_hotid.NEXTVAL, 'DANKL', 40, seq_h_lotid.NEXTVAL);

INSERT INTO hotels
VALUES (seq_h_hotid.NEXTVAL, 'KING LOUIE', 40, seq_h_lotid.NEXTVAL);

INSERT INTO hotels
VALUES (seq_h_hotid.NEXTVAL, 'HARRY', 40, seq_h_lotid.NEXTVAL);

INSERT INTO boards
VALUES(seq_board_id.NEXTVAL, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');

INSERT INTO boards
VALUES(seq_board_id.NEXTVAL, 'Y', 'N', 'N', 'Y', 'Y', 'N');

INSERT INTO boards
VALUES(seq_board_id.NEXTVAL, 'N', 'N', 'N', 'Y', 'Y', 'Y');

INSERT INTO boards
VALUES(seq_board_id.NEXTVAL, 'Y', 'N', 'Y', 'N', 'Y', 'Y');

INSERT INTO boards
VALUES(seq_board_id.NEXTVAL, 'N', 'N', 'N', 'N', 'N', 'Y');

INSERT INTO bills
VALUES(seq_bill_id.NEXTVAL, 'JOHN', 'SMITH', 9999, '19-MAR-2017', '29 WANGLE VILLAGE', 1234567891);

INSERT INTO payment_methods
VALUES (seq_payment_methods.NEXTVAL,8794762727483739,
'19/MAR/2017','AMBER RAWLINS',
'VISA DEBIT','HSBC');
INSERT INTO payment_methods
VALUES (seq_payment_methods.NEXTVAL,8794762727486739,
'18/MAR/2017','ALFIE ENGLAND',
'VISA DEBIT','NATWEST');
INSERT INTO payment_methods
VALUES (seq_payment_methods.NEXTVAL,8794762724483739,
'28/MAR/2017','BROOK SMITH',
'VISA DEBIT','NATIONWIDE');
INSERT INTO payment_methods
VALUES (seq_payment_methods.NEXTVAL,8794762717483739,
'20/OCT/2017','THOMAS WEAVER',
'VISA DEBIT','LLOYDS');
INSERT INTO payment_methods
VALUES (seq_payment_methods.NEXTVAL,8794762727583739,
'15/SEP/2017','ALAN MEADE',
'VISA DEBIT','BARCLAYS');

--TEAMS
INSERT INTO teams
VALUES (seq_teams.NEXTVAL,'SALES', 'PROMOTION OF COMPANY PRODUCTS TO CUSTOMERS');

INSERT INTO teams
VALUES (seq_teams.NEXTVAL,'ADMIN', 'TASKED WITH OVERSEEING THE RUNNING OF THE COMPANY');

INSERT INTO teams
VALUES (seq_teams.NEXTVAL,'FINANCE', 'OVERSEEING MONATARY TRANSACTIONS OF THE COMPANY');

INSERT INTO teams
VALUES (seq_teams.NEXTVAL,'LEGAL', 'IN CHRAGE OF LEGAL MATTERS REALTED TO THE COMPANY');

INSERT INTO teams
VALUES (seq_teams.NEXTVAL,'HR', 'CHARGED WITH ENFORCING PROBER WORKPLACE PRACTICE');

--FLIGHTS
INSERT INTO flights
VALUES (seq_flights.NEXTVAL, 'GATRN10928', 'ESPRN10928', 'GATWICK', 'SPAIN', '14/MAY/2017', '23/MAY/2017');

INSERT INTO flights
VALUES (seq_flights.NEXTVAL, 'MANAC92810', 'CHNAC92810', 'MANCHESTER', 'CHINA', '02/JUN/2017', '20/JUN/2017');

INSERT INTO flights
VALUES (seq_flights.NEXTVAL, 'EMAAM39812', 'MALAM39812', 'EAST MIDLANDS', 'MALTA', '27/JUN/2017', '07/JUL/2017');

INSERT INTO flights
VALUES (seq_flights.NEXTVAL, 'STNEJ98213', 'FRAEJ98213','STANSTED', 'FRANCE', '14/APR/2017', '03/MAY/2017');

INSERT INTO flights
VALUES (seq_flights.NEXTVAL, 'GLADA73281', 'NETDA73281', 'GLASGOW', 'NETHERLANDS', '14/SEP/2017', '23/SEP/2017');
